package proxy

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"stackfly/internal/config"
	"stackfly/internal/store"
)

type Caddy struct {
	cfg   *config.Config
	store *store.Store
}

func New(cfg *config.Config, store *store.Store) *Caddy {
	return &Caddy{cfg: cfg, store: store}
}

func (c *Caddy) EnsureRunning(ctx context.Context) error {
	cmd := exec.CommandContext(ctx, "docker", "inspect", c.cfg.CaddyContainer)
	if cmd.Run() == nil {
		running := exec.CommandContext(ctx, "docker", "inspect", "-f", "{{.State.Running}}", c.cfg.CaddyContainer)
		out, _ := running.Output()
		if strings.TrimSpace(string(out)) == "true" {
			return nil
		}
		start := exec.CommandContext(ctx, "docker", "start", c.cfg.CaddyContainer)
		return start.Run()
	}

	caddyFile := filepath.Join(c.cfg.CaddyDir, "Caddyfile")
	if _, err := os.Stat(caddyFile); os.IsNotExist(err) {
		os.WriteFile(caddyFile, []byte("# StackFly managed Caddyfile\n"), 0644)
	}

	cmd = exec.CommandContext(ctx, "docker", "run", "-d",
		"--name", c.cfg.CaddyContainer,
		"--network", c.cfg.DockerNetwork,
		"-p", "80:80",
		"-p", "443:443",
		"-v", c.cfg.CaddyDir+":/etc/caddy",
		"-v", "stackfly-caddy-data:/data",
		"-v", "stackfly-caddy-config:/config",
		"--restart", "unless-stopped",
		"caddy:latest",
	)
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to start caddy: %s: %w", string(out), err)
	}
	return nil
}

func (c *Caddy) Regenerate(ctx context.Context) error {
	grouped, err := c.store.GetAllDomainsGrouped()
	if err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("# Auto-generated by StackFly - do not edit\n\n")

	for appName, domains := range grouped {
		if len(domains) == 0 {
			continue
		}
		svcName := fmt.Sprintf("%s-web", appName)

		var httpDomains, httpsDomains []string
		for _, d := range domains {
			if d.SSL {
				httpsDomains = append(httpsDomains, d.FQDN)
			} else {
				httpDomains = append(httpDomains, "http://"+d.FQDN)
			}
		}

		if len(httpDomains) > 0 {
			b.WriteString(fmt.Sprintf("%s {\n", strings.Join(httpDomains, ", ")))
			b.WriteString(fmt.Sprintf("\treverse_proxy %s:5000\n", svcName))
			b.WriteString("}\n\n")
		}
		if len(httpsDomains) > 0 {
			b.WriteString(fmt.Sprintf("%s {\n", strings.Join(httpsDomains, ", ")))
			b.WriteString(fmt.Sprintf("\treverse_proxy %s:5000\n", svcName))
			b.WriteString("}\n\n")
		}
	}

	caddyFile := filepath.Join(c.cfg.CaddyDir, "Caddyfile")
	if err := os.WriteFile(caddyFile, []byte(b.String()), 0644); err != nil {
		return err
	}

	return c.reload(ctx)
}

func (c *Caddy) Update(ctx context.Context) error {
	pull := exec.CommandContext(ctx, "docker", "pull", "caddy:latest")
	pull.Stdout = os.Stdout
	pull.Stderr = os.Stderr
	if err := pull.Run(); err != nil {
		return fmt.Errorf("pull failed: %w", err)
	}

	exec.CommandContext(ctx, "docker", "stop", c.cfg.CaddyContainer).Run()
	exec.CommandContext(ctx, "docker", "rm", c.cfg.CaddyContainer).Run()

	return c.EnsureRunning(ctx)
}

func (c *Caddy) reload(ctx context.Context) error {
	cmd := exec.CommandContext(ctx, "docker", "exec", c.cfg.CaddyContainer, "caddy", "reload", "--config", "/etc/caddy/Caddyfile")
	if out, err := cmd.CombinedOutput(); err != nil {
		if strings.Contains(string(out), "No such container") {
			return nil
		}
		return fmt.Errorf("caddy reload failed: %s: %w", string(out), err)
	}
	return nil
}
